defaults:
  - dataset: single_cube_1texture
  - inputs: all
  - model: base

experiment: fast_dev
seed: null
wandb_main: False
suffix: ''
save_epoch: 15
sanity_steps: 0
max_epoch: 10000
val_check_percent: 1.0
val_check_interval: 15
resume: null

batch_size: 8
num_workers: 8
lr: 0.0001
lambda_l1: 1
lambda_content: 0.005

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
