defaults:
  - dataset: single_cube

model:
  generator_ngf: 32
  discriminator_ngf: 32

gan_loss_type: wgan_gp

experiment: fast_dev
seed: null
save_epoch: 1
sanity_steps: 0
max_epoch: 10000
val_check_percent: 1.0
val_check_interval: 1
resume: null

batch_size: 8
num_workers: 8
lr: 0.0001
lambda_g: 1
lambda_d: 1
lambda_gp: 10
only_l: True

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  launcher:
    cpus_per_task: 8
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 64
    nodes: 1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: debug
    exclude: char,pegasus,seti,tarsonis