defaults:
  - dataset: graph_cube_textures_official

experiment: fast_dev
seed: null
save_epoch: 1
sanity_steps: 0
max_epoch: 5000
val_check_percent: 1.0
val_check_interval: 10
print_interval: 1
resume: null

batch_size: 8
num_workers: 8
lr: 0.0001

proc: 0
n_proc: 1

wandb_main: False
suffix: ''

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
