defaults:
  - dataset: single_cube_textures_overfit_to_one
  - inputs: 2d_retrieval_partial_texture
  - model: singlecube_colors

model:
  discriminator_ngf: ${model.input_texture_ngf}

experiment: fast_dev
seed: null
wandb_main: False
suffix: ''
save_epoch: 15
sanity_steps: 0
max_epoch: 10000
val_check_percent: 1.0
val_check_interval: 15
resume: null

batch_size: 8
num_workers: 8
lr: 0.0001
lambda_regr_l: 10
lambda_regr_ab: 10
lambda_content: 0.075
lambda_style: 0.0075
lambda_ntxent: 1
lambda_regr_retr: 5
regression_loss_type: l2
temperature: 0.1
phase_change_epochs:
  - 150
  - 150
  - 150
current_phase: 0

dictionary:
  patch_size: 16
  K: 8
  retrieval_dir: data/retrieval/SingleShape__CubeTextures/official/12052106_retrieval_base_t0.2_1view/_ckpt_epoch=2474/8/

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .

