defaults:
  - dataset: single_cube_textures_overfit_to_one
  - inputs: 2d_only_partial_texture

num_proc: 1
proc: 0
fenc_nf: 32
fenc_zdim: 128

dictionary:
  patch_size: 16
  K: 8
  flann_num_workers: 0
  batch_size: 8
  num_workers: 8

experiment: fast_dev
seed: null
wandb_main: False
suffix: ''
save_epoch: 30
sanity_steps: 0
max_epoch: 10000
val_check_percent: 1.0
val_check_interval: 30
resume: null
scheduler: null

batch_size: 12
num_workers: 8
lr: 0.0001

temperature: 0.1

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
