defaults:
  - dataset: single_cube_textures
  - inputs: 2d_only_partial_texture

mode:
  - visualize

num_proc: 1
proc: 0
retrieval_dir: data/
retrieval_ckpt: runs/12052106_retrieval_base_t0.2_1view/_ckpt_epoch=2474.ckpt
fenc_nf: 32
fenc_zdim: 128

dictionary:
  patch_size: 16
  K: 8
  flann_num_workers: 0
  batch_size: 8
  num_workers: 0

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
