defaults:
  - dataset: graph_cube_textures_official

experiment: fast_dev
seed: null
save_epoch: 1
sanity_steps: 1
max_epoch: 250
scheduler: null
val_check_percent: 1.0
val_check_interval: 5
print_interval: 500
resume: null

weight_decay: 0
use_augmentations: False
use_blur: True
use_self_attn: False
nf: 128

views_per_sample: 4
batch_size: 3
num_workers: 8
lr: 0.000035

proc: 0
n_proc: 1

wandb_main: False
suffix: ''

method: face
conv: attention


w_l1: 1
w_style: 0
w_content: 0

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
