defaults:
  - dataset: single_cube_textures_overfit_to_one
  - inputs: 2d_retrieval_partial_texture
  - model: singlecube_colors

dataset:
  num_database_textures: 16

dictionary:
  patch_size: 16
  K: 4
  flann_num_workers: 0
  batch_size: 8
  num_workers: 0

experiment: fast_dev
seed: null
wandb_main: False
suffix: ''
save_epoch: 15
sanity_steps: 0
max_epoch: 10000
val_check_percent: 1.0
val_check_interval: 15
resume: null
scheduler: null

batch_size: 8
num_workers: 8
lr: 0.0001

warmup_epochs_constrastive: 120
temperature: 0.1
lambda_regr_l: 10
lambda_regr_ab: 5
lambda_content: 0.02
lambda_style: 500
lambda_ntxent: 1
regression_loss_type: l2

fenc_nf: 32
fenc_zdim: 128

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .

