# @package _group_
name: '3D-FUTURE/Sofa'
preload: True
views_per_shape: 24
data_dir: 'data'
splits_dir: 'official'
texture_map_size: 384
render_size: 256
mesh_dir: '3D-FUTURE-model/Sofa'
color_space: lab