# @package _group_
name: 'SingleShape/completion2x_CubeTextures'
preload: False
views_per_shape: 12
data_dir: 'data'
splits_dir: 'official'
texture_map_size: 128
render_size: 256
mesh_dir: 'SingleShape-model/completion2x_CubeTextures'
color_space: lab