# @package _group_
name: 'SingleShape/CubeTextures'
preload: False
views_per_shape: 1
data_dir: 'data'
splits_dir: 'official'
texture_map_size: 128
render_size: 256
mesh_dir: 'SingleShape-model/CubeTextures'
color_space: lab