# @package _group_
name: 'SingleShape/Cube'
preload: True
views_per_shape: 24
data_dir: 'data'
splits_dir: 'overfit_003'
texture_map_size: 384
render_size: 256
mesh_dir: 'SingleShape-model/Cube'
color_space: lab