# @package _group_
name: 'SingleShape/CubeSingleTexture02'
preload: False
views_per_shape: 24
data_dir: 'data'
splits_dir: 'official'
texture_map_size: 128
render_size: 256
mesh_dir: 'SingleShape-model/CubeSingleTexture02'
color_space: lab