# @package _group_
name: 'TestShape/Cube'
preload: False
views_per_shape: 12
data_dir: 'data'
splits_dir: 'overfit'
texture_map_size: 128
render_size: 256
mesh_dir: 'TestShape-model/Cube'
color_space: lab